# Generated by Django 4.1 on 2024-02-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionChat', '0002_alter_empresa_options_alter_mensaje_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='nombre_sucursal',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
