# Generated by Django 4.1 on 2024-02-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionChat', '0003_sucursal_nombre_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sucursal_matriz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriz', to='EducacionChat.sucursal'),
        ),
    ]
