# Generated by Django 4.1 on 2024-02-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionChat', '0004_empresa_sucursal_matriz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='sucursal_matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriz', to='EducacionChat.sucursal'),
        ),
    ]
