# Generated by Django 4.1 on 2024-02-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionChat', '0005_alter_empresa_sucursal_matriz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='dispositivos_en_casa',
            field=models.IntegerField(),
        ),
    ]
