# Generated by Django 4.1 on 2024-02-29 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionChat', '0006_alter_trabajador_dispositivos_en_casa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['tiempo'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='timestamp',
            new_name='tiempo',
        ),
    ]
