# Generated by Django 4.1 on 2024-03-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionChat', '0007_alter_mensaje_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='sesion_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
