# Generated by Django 4.1 on 2024-03-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionChat', '0009_alter_mensaje_pregunta_alter_mensaje_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='sesion_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
